language: node_js
node_js:
- '6'
cache:
  directories: "-node_modules"
after_failure:
- "./errorShots"
script:
- npm install
- npm run regression
- npm run mobile
- npm run finus


addons:
  browserstack:
    username: "manvinderverma1"
    access_key: "PMM7UxGeAiQozg5aCWia"
sudo: false
