language: node_js
node_js:
  - "0.10"
cache:
  directories:
    - node_modules
install:
- npm install

run:
- npm run regression


addons:
  browserstack:
    username: "manvinderatfinde1"
    access_key: "AtYbSCsQujdwqXpbwYZc"