language: node_js
node_js:
  - "4.3"

script:
  - npm install
  - npm install wdio-spec-reporter
  - npm run multiple

addons:
  browserstack:
    username: "manvinderverma1"
    access_key: "PMM7UxGeAiQozg5aCWia"