var page = require('./page');

var insPage = Object.create(page, {
  // fti form
  singleTripTab: { get: function () { return $('.fti-form>ul>li:nth-child(1)'); } },
  multiTrip: { get: function () { return $('a.fti-tab-multi'); } },
  multiTripTab: { get: function () { return $('.fti-form>ul>li:nth-child(2)'); } },
  quoteButton: { get: function () { return $('div.active .fin-btn-green'); } },
  countryError: { get: function () { return $('div.active .one_half.clearfix:first-child .error-message'); } },
  countryPanel: { get: function () { return $('.country-panel'); } },
  countryUk: { get: function () { return $('.country-panel button[data-destination-id="304"]'); } },
  countryFrance: { get: function () { return $('.country-panel button[data-destination-id="73"]'); } },
  country: { get: function () { return $('div.active .fti-destination-wrap li div'); } },
  countryPanelClose: { get: function () { return $('.country-panel .icon-cross'); } },
  datesError: { get: function () { return $('div.active .last_column.error .error-message'); } },
  ageError: { get: function () { return $('div.active .one_third .error-message'); } },
  countryInput: { get: function () { return $('div.active .select2-search-field>input[type="text"]'); } },
  countryDropdownMatch: { get: function () { return $('.select2-drop .select2-match'); } },
  countryDropdown: { get: function () { return $('.select2-drop-active'); } },
  fromDate: { get: function () { return $('div.active [name="fti_from"]'); } },
  toDate: { get: function () { return $('#fti-single-trip .fti-to-wrap>span'); } },
  nextDate: { get: function () { return $('.datepicker-days th.next'); } },
  rowDate: { get: function () { return $('.datepicker-days tr:first-child>td:nth-child(7)'); } },
  travellerAge1: { get: function () { return $('div.active .fti-age[data-active="true"]'); } },
  receiveQuote: { get: function () { return $('div.active input[name="fti_email"]'); } },
  receiveQuoteYes: { get: function () { return $('div.active label:nth-child(2) [name="option-receive-quote"]'); } },
  receiveQuoteNo: { get: function () { return $('div.active label:nth-child(3) [name="option-receive-quote"]'); } },
  retrieveLink: { get: function () { return $('.fti-retrieve a'); } },
  // fti results
  ftiTable: { get: function () { return $('.fti-result-table'); } },
  ftiSummary: { get: function () { return $('#quote-title'); } },
  ftiRef: { get: function () { return $('#fti-reference'); } },
  ftiMoreInfo: { get: function () { return $('.fti-result-table tr:nth-child(1) .fti-product-extra-text'); } },
  ftiMoreInfoSection: { get: function () { return $('.fti-product-extra-block'); } },
  ftiHideInfo: { get: function () { return $('.fti-product-extra-block'); } },
  ftiPrice1: { get: function () { return $('.fti-result-table tr:first-child .fti-price-quote'); } },
  sortPrice: { get: function () { return $('.fti-fin-price.tablesorter-headerAsc'); } },
  couponResult: { get: function () { return $('tr:first-child .fti-coupon>span'); } },
  cruiseResult: { get: function () { return $('tr:first-child .fti-filter-icons>a>i'); } },
  noFtiResult: { get: function () { return $('.has-margin-bottom-medium'); } },
  // filters
  clearAllFilter: { get: function () { return $('.form__reset'); } },
  couponFilter: { get: function () { return $('[name="coupon_discount"]'); } },
  cruiseFilter: { get: function () { return $('[name="cruise_specific"]'); } },
  skiFilter: { get: function () { return $('[name="ski"]'); } },
  // fti edit quote
  addTraveller: { get: function () { return $('div.active .icon-plus'); } },
  travellerAge2: { get: function () { return $('div.active .fti-age[name="traveller_age1"]'); } },
  addTravellerAge3: { get: function () { return $('div.active .fti-age[name="traveller_age2"]'); } },
  removeTraveller: { get: function () { return $('div.active .icon-minus'); } },
  removeCountry: { get: function () { return $('div.active .select2-search-choice-close'); } },
  updateResultsButton: { get: function () { return $('.fin-btn.btn-secondary'); } },
  destinationError: { get: function () { return $('div.active .form-group:first-child .error-message'); } },
  saveSearchLink: { get: function () { return $('.fti-save-search'); } },
  saveSearch: { get: function () { return $('#fti_save_quote .fin-btn-green'); } },
  saveSearchError: { get: function () { return $('.fti-save-retrieve #fti_save_quote .error-message'); } },
  saveSearchInput: { get: function () { return $('#fti_save_quote input'); } },
  saveSearchStatus: { get: function () { return $('#fti_save_quote li'); } },
  retrieveQuoteLink: { get: function () { return $('.fti-retrieve-search'); } },
  retrieveQuoteButton: { get: function () { return $('#fti_retrieve_quote>button'); } },
  retrieveQuoteError: { get: function () { return $('#fti_retrieve_quote .error-message'); } },
  retrieveQuoteInput: { get: function () { return $('#fti_retrieve_quote input'); } },
  newSearchLink: { get: function () { return $('.fti-new-search>a:nth-child(2)'); } },
  finBreadcrumb: { get: function () { return $('div>small> a:first-child'); } },
  ftiBreadcrumb: { get: function () { return $('a=Travel Insurance'); } },
  newSearchLink: { get: function () { return $('.fti-new-search a[href="/travel-insurance"]'); } },
  // loadingSpinner
  register: { get: function () { return $('.btn-nav--login i:nth-child(1)'); } },
  emailInput: { get: function () { return $('#user-login-signin-email'); } },
  passwordInput: { get: function () { return $('#user-login-signin-password'); } },
  signInButton: { get: function () { return $('div[aria-labelledby="tabpanel-1"] button[name="submit"]'); } },
  greetings: { get: function () { return $('.large-extra-info'); } },
  // fli
  fliCompareButton: { get: function () { return $('.u-grid>div:first-child button'); } },
  submitFli: { get: function () { return $('about-you .btn'); } },
  sexError: { get: function () { return $('.relative>div:first-child span'); } },
  dobError: { get: function () { return $('.relative>div:nth-child(2)>div:first-child span'); } },
  stateError: { get: function () { return $('.relative>div:nth-child(2)>div:nth-child(2) span'); } },
  smokerError: { get: function () { return $('.relative>div:nth-child(3)>div:first-child>.clearfix span'); } },
  occupationError: { get: function () { return $('.relative>div:nth-child(3)>div:nth-child(2)>span.form__error'); } },
  dayInput: { get: function () { return $('#birthdate'); } },
  monthInput: { get: function () { return $('[name="birthmonth"]'); } },
  yearInput: { get: function () { return $('[name="birthyear"]'); } },
  occupationInput: { get: function () { return $('[name="occupation"]'); } },
  occupationDropdown: { get: function () { return $('.awesomplete'); } },
  occupation1: { get: function () { return $('.awesomplete li:first-child'); } },
  maleButton: { get: function () { return $('.icon-male'); } },
  femaleButton: { get: function () { return $('.icon-female'); } },
  stateSelect: { get: function () { return $('#countrystate'); } },
  smokerButton: { get: function () { return $('[for="smoker"]'); } },
  nonSmokerButton: { get: function () { return $('[for="non_smoker"]'); } },
  // fli level of cover
  lifeCoverForm: { get: function () { return $('lifeinsurance-app'); } },
  lifeCoverButton: { get: function () { return $('.fli-life-cover .btn-secondary'); } },
  lifeCoverError: { get: function () { return $('span.form__error'); } },
  lifeCoverValue: { get: function () { return $('life-cover .form__range__output'); } },
  incomeCoverValue: { get: function () { return $('income-protection-cover .form__range__output'); } },
  traumaCoverValue: { get: function () { return $('trauma-cover .form__range__output'); } },
  tpdCoverValue: { get: function () { return $('tpd-cover .form__range__output'); } },
  calcMethodology: { get: function () { return $('.fli-calculator-methodology>a'); } },
  // calculator
  calcButton: { get: function () { return $('.fli-level-calculator>button'); } },
  step1Label: { get: function () { return $('[name="step-1"]>div>.fin-text-grey'); } },
  step1Button: { get: function () { return $('[name="step-1"] button'); } },
  step1Error: { get: function () { return $('.fli-cover-calculator__next-step .form__error'); } },
  withChildren: { get: function () { return $('[for="with_children"]'); } },
  noChildren: { get: function () { return $('[for="no_children"]'); } },
  childrenInput: { get: function () { return $('#children'); } },
  ageInput: { get: function () { return $('#youngestChildAge'); } },
  incomeInput: { get: function () { return $('#income'); } },
  step2Label: { get: function () { return $('[name="step-2"]>div>.fin-text-grey'); } },
  step2Button: { get: function () { return $('[name="step-2"] button'); } },
  withHomeLoan: { get: function () { return $('[for="with_home_loan"]'); } },
  noHomeLoan: { get: function () { return $('[for="no_home_loan"]'); } },
  homeLoanInput: { get: function () { return $('#homeLoan'); } },
  withDebt: { get: function () { return $('[for="with_debt"]'); } },
  noDebt: { get: function () { return $('[for="no_debt"]'); } },
  debtInput: { get: function () { return $('#debt'); } },
  previousButton: { get: function () { return $('.fli-cover-calculator__step-controls>div:first-child button'); } },
  cancelButton: { get: function () { return $('.fli-cover-calculator .last_column button'); } },
  step3Label: { get: function () { return $('[name="step-3"]>div>.fin-text-grey'); } },
  step3Button: { get: function () { return $('[name="step-3"] button'); } },
  calcLifeCoverValue: { get: function () { return $('[for="calcLifeCover"] span'); } },
  calcIncomeCoverValue: { get: function () { return $('[for="calcIncome"] span'); } },
  calcTraumaCoverValue: { get: function () { return $('[for="calcTrauma"] span'); } },
  calcTpdCoverValue: { get: function () { return $('[for="calcTpd"] span'); } },
  calcLifeCoverCheckbox: { get: function () { return $('#calcLifeCover'); } },
  calcIncomeCheckbox: { get: function () { return $('#calcIncome'); } },
  calcTraumaCheckbox: { get: function () { return $('#calcTrauma'); } },
  calcTpdCheckbox: { get: function () { return $('#calcTpd'); } },
  // fli results
  fliResults: { get: function () { return $('.fli-portfolios'); } },
  fliNoResults: { get: function () { return $('.fli-no-results h4'); } },
  fliInfo: { get: function () { return $('.fli-results-heading__sub-headline>strong:first-child'); } },
  fliState: { get: function () { return $('.fli-results-heading__sub-headline>strong:nth-child(2)'); } },
  fliCover: { get: function () { return $('.fli-results-heading__sub-headline>raw>strong'); } },
  fliDirectProvider: { get: function () { return $('results-filter label'); } },
  fliDirectProviderNote: { get: function () { return $('direct-providers>div>p'); } },
  lifeCoverSlider: { get: function () { return $('life-cover .noUi-origin'); } },
  incomeCoverSlider: { get: function () { return $('income-protection-cover .noUi-origin'); } },
  traumaCoverSlider: { get: function () { return $('trauma-cover .noUi-origin'); } },
  tpdCoverSlider: { get: function () { return $('tpd-cover .noUi-origin'); } },
  updateFilter: { get: function () { return $('.fli-results-filter section>[type="submit"]'); } },
  fliViewDetails: { get: function () { return $('li:first-child portfolio .btn-link--brand'); } },
  viewDetailsTab: { get: function () { return $('li:first-child more-info[visible="true"] a'); } },
  viewDetailsIncomeTab: { get: function () { return $('li:first-child a[name="income_protection"]'); } },
  viewDetailsIncomeTabActive: { get: function () { return $('li:first-child a[name="income_protection"].is-tab-active'); } },
  viewDetailsTraumaTab: { get: function () { return $('results-table>ul>li:first-child a[name="trauma"]'); } },
  viewDetailsTraumaTabActive: { get: function () { return $('li:first-child a[name="trauma"].is-tab-active'); } },
  viewDetailsTpdTab: { get: function () { return $('li:first-child a[name="tpd"]'); } },
  viewDetailsTpdTabActive: { get: function () { return $('li:first-child a[name="tpd"].is-tab-active'); } },
  viewDetailsLifeTab: { get: function () { return $('results-table>ul>li:first-child a[name="life"]'); } },
  viewDetailsLifeTabActive: { get: function () { return $('li:first-child a[name="life"].is-tab-active'); } },
  viewDetailsSection: { get: function () { return $('.fli-portfolios__item:first-child .is-selected-tab'); } },
  result1Provider: { get: function () { return $('li:first-child h4'); } },
  enquire1: { get: function () { return $('li:first-child div>.btn-success'); } },
  fliprice1: { get: function () { return $('li:first-child .fli-premium-total'); } },
  fliSortPrice: { get: function () { return $('.table-sorter button>span'); } },
  traumaTabSection: { get: function () { return $('more-info[visible="true"] li:nth-child(2) section'); } },
  thankyouMessage: { get: function () { return $('h3.text-xxx-large'); } },
  // fli enquire
  enquire1Provider: { get: function () { return $('modal-enquire-form .last_column h4'); } },
  enquireModal: { get: function () { return $('.fli-enquire-form'); } },
  enquireCloseButton: { get: function () { return $('.fli-enquire-form .close>i'); } },
  enquireSubmit: { get: function () { return $('.fli-enquire-form .btn'); } },
  enquireFnameError: { get: function () { return $('.form>.form__group:first-child>span'); } },
  enquireEmailError: { get: function () { return $('.form>.form__group:nth-child(2)>span'); } },
  enquireNumberError: { get: function () { return $('.form>.form__group:nth-child(3)>span'); } },
  enquireIncomeError: { get: function () { return $('.form>.form__group:nth-child(4)>span'); } },
  enquireContactError: { get: function () { return $('.form>.form__group:nth-child(5)>span'); } },
  enquireNameInput: { get: function () { return $('#fullname'); } },
  enquireEmailInput: { get: function () { return $('#email'); } },
  enquirePhoneInput: { get: function () { return $('#phone'); } },
  enquireContactSelect: { get: function () { return $('#schedule'); } },
  enquireSuccess: { get: function () { return $('.btn__success.icon-tick'); } },
  // fhi
  searchPoliciesButton: { get: function () { return $('#healthinsuranceapp [type="submit"]'); } },
  lifeStageError: { get: function () { return $('form>div:nth-child(4) .fhi-form__error'); } },
  coverError: { get: function () { return $('form>div:nth-child(5) .fhi-form__error'); } },
  postcodeError: { get: function () { return $('form>div:nth-child(6) .fhi-form__error'); } },
  postCodeInput: { get: function () { return $('.react-autosuggest__input'); } },
  postCodeAutoSuggest: { get: function () { return $('#react-autowhatever-postcode_suburb'); } },
  postCode1: { get: function () { return $('#react-autowhatever-postcode_suburb>ul>li:first-child'); } },
  moreOptionsButton: { get: function () { return $('.about-you__more-options>button'); } },
  moreOptionsSection: { get: function () { return $('form>div:nth-child(7)'); } },
  excess: { get: function () { return $('#excess_option>[value="1"]'); } },
  excessState: { get: function () { return $('#excess_option'); } },
  levelOfHospital: { get: function () { return $('#hospital_cover_level>[value="compare_all"]'); } },
  levelOfHospitalState: { get: function () { return $('#hospital_cover_level'); } },
  incomeTierDefault: { get: function () { return $('#income_tier>[value="2"]'); } },
  incomeTierCouple: { get: function () { return $('#income_tier>[value="6"]'); } },
  ageTierDefault: { get: function () { return $('#age_tier>[value="2"]'); } },
  femaleCover: { get: function () { return $('[for="single_female"]>span'); } },
  maleCover: { get: function () { return $('[for="single_male"]>span'); } },
  coupleCover: { get: function () { return $('[for="couple"]>span'); } },
  familyCover: { get: function () { return $('[for="family"]>span'); } },
  singleParentCover: { get: function () { return $('[for="single_parent"]>span'); } },
  combinedCover: { get: function () { return $('[for="combined"]>span'); } },
  hospitalCover: { get: function () { return $('[for="hospital"]>span'); } },
  extrasCover: { get: function () { return $('[for="extras"]>span'); } },
  // fhi results
  fhiResults: { get: function () { return $('.results-table'); } },
  fhiInfoSummary: { get: function () { return $('.summary-section p>strong:first-child'); } },
  fhiCoverSummary: { get: function () { return $('.summary-section p>strong:nth-child(2)'); } },
  fhiPostCodeSummary: { get: function () { return $('.summary-section p>strong:nth-child(3)'); } },
  fhiLoading: { get: function () { return $('.fhi-loading-pulse'); } },
  resultPolicies: { get: function () { return $('.results-table>div>div:first-child.comparison-header__column'); } },
  sortByRelevance: { get: function () { return $('select.luna-select>option[value="spot_rank-desc"]'); } },
  sortBySelect: { get: function () { return $('.comparison-header>div>select'); } },
  // fhi combined results
  combinedResultHospital: { get: function () { return $('.comparison-table>div:first-child div:first-child>h4'); } },
  combinedResultExtras: { get: function () { return $('.comparison-table>div:first-child div:nth-child(2)>h4'); } },
  combinedResultExcess: { get: function () { return $('.comparison-table>div:first-child div:first-child>ul>li:last-child'); } },
  // fhi hospital results
  hospitalResultRoom: { get: function () { return $('.comparison-table__item:first-child ul:nth-child(2)>li:first-child'); } },
  hospitalResultLevel: { get: function () { return $('.comparison-table__item:first-child ul:nth-child(2)>li:nth-child(2)'); } },
  hospitalResultExcess: { get: function () { return $('.comparison-table__item:first-child ul:nth-child(2)>li:nth-child(3)'); } },
  // fhi extras results
  ExtrasResultDental: { get: function () { return $('.comparison-table__item:first-child ul:nth-child(2)>li:first-child'); } },

  fhiEnquireButton: { get: function () { return $('.comparison-table>div button.luna-button--success'); } },
  fhiResultPrice1: { get: function () { return $('.comparison-table>div:first-child .premium-total__amount'); } },
  fhiResultProvider1: { get: function () { return $('.comparison-table>div:first-child img'); } },
  fhiResultLevelOfCover1: { get: function () { return $('.comparison-table>div:first-child div:first-child>ul>li:nth-child(2)'); } },
  fhiViewDetailsButton: { get: function () { return $('.comparison-table>div:first-child .comparison-table__more-info>button'); } },
  fhiModal: { get: function () { return $('.dialog-screen[aria-hidden="false"]'); } },
  fhiSplitResult: { get: function () { return $('.health-provider-logo--split'); } },
  splitResultHospitalPrice: { get: function () { return $('div:nth-child(1)>h4>.comparison-table__split-pricing'); } },
  splitResultExtrasPrice: { get: function () { return $('div:nth-child(2)>h4>.comparison-table__split-pricing'); } },
  fhiCompareLabel1: { get: function () { return $('.comparison-table>div:first-child label'); } },
  fhiCompareLabel2: { get: function () { return $('.comparison-table>div:nth-child(2) label'); } },
  fhiCompareLabel3: { get: function () { return $('.comparison-table>div:nth-child(3) label'); } },
  fhiCompareLabel4: { get: function () { return $('.comparison-table>div:nth-child(4) label'); } },
  fhiCompareLabel5: { get: function () { return $('.comparison-table>div:nth-child(5) label'); } },
  fhiCompareCheckbox1: { get: function () { return $('.comparison-table>div:first-child input'); } },
  fhiCompareCheckbox2: { get: function () { return $('.comparison-table>div:nth-child(2) input'); } },
  fhiCompareCheckbox3: { get: function () { return $('.comparison-table>div:nth-child(3) input'); } },
  fhiCompareCheckbox4: { get: function () { return $('.comparison-table>div:nth-child(4) input'); } },
  fhiCompareCheckbox5: { get: function () { return $('.comparison-table>div:nth-child(5) input'); } },
  // fhi compare band
  fhiCompareBand: { get: function () { return $('.comparison-band.is-shown'); } },
  fhiProviders: { get: function () { return $$('.comparison-band__column--providers li').length; } },
  fhiCompareButton: { get: function () { return $('.comparison-band__column .btn'); } },
  fhiXButton: { get: function () { return $('.comparison-band__column--providers li:nth-child(2)>.comparison-band__remove'); } },
  fhiClearAll: { get: function () { return $('.comparison-band__clear'); } },
  // fhi compare modal
  fhiCompareModal: { get: function () { return $('.dialog-screen[aria-hidden="false"] .comparison-modal'); } },
  fhiCompareExtras1: { get: function () { return $('.comparison-panel:first-child .feature_1 button'); } },
  fhiCompareModalAllProviders: { get: function () { return $$('.comparison-panel-container>div').length; } },
  fhiCompareModalAllX: { get: function () { return $$('.comparison-panel__close').length; } },
  fhiCompareModalAllPrices: { get: function () { return $$('.comparison-modal .premium-total__amount').length; } },
  fhiCompareModalAllHospitals: { get: function () { return $$('.comparison-panel__hospital').length; } },
  fhiCompareModalAllExtras: { get: function () { return $$('.comparison-panel__extras').length; } },
  fhiCompareModalProvider1: { get: function () { return $('.comparison-panel:first-child .feature_1 .is-expanded'); } },
  fhiCompareModalClose: { get: function () { return $('.comparison-panel__close'); } },
  fhiCompareModalProvider2: { get: function () { return $('.comparison-panel:nth-child(2) .feature_1 .is-expanded'); } },
  fhiCompareModalProvider3: { get: function () { return $('.comparison-panel:nth-child(3) .feature_1 .is-expanded'); } },
  fhiCompareModalProvider4: { get: function () { return $('.comparison-panel:nth-child(4) .feature_1 .is-expanded'); } },
  fhiCompareModalX1: { get: function () { return $('.comparison-panel:first-child button>.icon-cross'); } },
  fhiCompareModalX2: { get: function () { return $('.comparison-panel:nth-child(2) button>.icon-cross'); } },
  fhiCompareModalX3: { get: function () { return $('.comparison-panel:nth-child(3) button>.icon-cross'); } },
  fhiCompareModalX4: { get: function () { return $('.comparison-panel:nth-child(4) button>.icon-cross'); } },

  // fhi view details
  fhiViewDetailsTopPanel: { get: function () { return $('.modal-info__panel--top'); } },
  fhiViewDetailsHospital: { get: function () { return $('.modal-info__panel--hospital'); } },
  fhiViewDetailsExtras: { get: function () { return $('.modal-info__panel--extras'); } },
  fhiViewDetailsProvider: { get: function () { return $('.modal-info__panel--top img'); } },
  fhiViewDetailsAmount: { get: function () { return $('.dialog-screen[aria-hidden="false"] .premium-total__amount'); } },
  fhiViewDetailsLevel: { get: function () { return $('.modal-info__panel--hospital .fin-text-grey'); } },
  fhiViewDetailsExcess: { get: function () { return $('.comparison-panel__hospital-group>div:nth-child(2)>span'); } },
  fhiViewDetailsCovered: { get: function () { return $('.modal-info__legend-item:nth-child(2)'); } },
  fhiViewDetailsRestricted: { get: function () { return $('.modal-info__legend-item:nth-child(4)'); } },
  fhiViewDetailsNotCovered: { get: function () { return $('.modal-info__legend-item:nth-child(6)'); } },
  fhiViewDetailsContact1: { get: function () { return $('.modal-info__panel--top .provider-contact__phone'); } },
  fhiViewDetailsContact2: { get: function () { return $('.modal-info__cta-button-container .provider-contact__phone'); } },
  fhiViewDetailsPodiatry: { get: function () { return $('.extras-group:last-child button'); } },
  fhiViewDetailsPodiatryExpanded: { get: function () { return $('.extras-group:last-child button.is-expanded'); } },
  fhiViewDetailsAmbulanceExpanded: { get: function () { return $('.extras-group:nth-child(7) button.is-expanded'); } },
  // fhi enquire
  fhiEnquireForm: { get: function () { return $('.dialog-screen[aria-hidden="false"] .modal-info>.fhi-enquire-form'); } },
  fhiEnquireBackButton: { get: function () { return $('.dialog-screen[aria-hidden="false"] button[aria-label="Back"]'); } },
  fhiEnquireCloseButton: { get: function () { return $('.dialog-screen[aria-hidden="false"] button[aria-label="Close"]'); } },
  fhiEnquireSubmitButton: { get: function () { return $('.modal-info form button[name="submit"]'); } },
  fhiEnquireNameError: { get: function () { return $('.dialog-screen[aria-hidden="false"] div:first-child>div.is-invalid>span'); } },
  fhiEnquirePhoneError: { get: function () { return $('.dialog-screen[aria-hidden="false"] div:nth-child(3)>div.is-invalid>span'); } },
  fhiEnquireNameInput: { get: function () { return $('#name'); } },
  // fhi filter
  fhiSplitFilterLabel: { get: function () { return $('[for="split_policies"]'); } },
  fhiSplitFilter: { get: function () { return $('#split_policies'); } },
  fhiExtrasFilterTab: { get: function () { return $('[href="#extras-cover"]'); } },
  fhiHospitalFilterTab: { get: function () { return $('[href="#hospital-cover"]'); } },

  /**
   * define or overwrite page methods
   */
  openFti: { value: function() {
    page.open.call(this, 'travel-insurance');
  } },

  openFli: { value: function() {
    page.open.call(this, 'life-insurance');
  } },

  openFhi: { value: function() {
    page.open.call(this, 'health-insurance');
  } },

  getQuote: { value: function() {
    this.quoteButton.click();
  } },

  getFli: { value: function() {
    this.submitFli.click();
  } },

  getLifeCover: { value: function() {
    this.lifeCoverButton.click();
  } },

  getFhi: { value: function() {
    this.searchPoliciesButton.click();
  } },

  getFhiCompare: { value: function() {
    this.fhiCompareButton.click();
  } }
});

module.exports = insPage;
